### PR TITLE
Fix typo bonk->bank

### PR DESCRIPTION
**Pull request by Radivarig**

### CODE REVIEW

**Comment by linas** [comment]
It's not a typo, there is a naming conflict with some other opencog component called "attentionbank".  Maybe the cogserver module, not sure.

I could merge this, but I suspect something else will break as a result ...

**Comment by linas** [comment]
I'm just not sure what to do .. merge, and cross fingers?  This is a very lightly used (almost unused) subsystem.

**Comment by Radivarig** [comment]
Oh :) I guess it's better to wait until confirmed.
This is what I found with grep on some master branches:
```
λ ls
atomspace  cogserver  cogutil  link-grammar  moses  opencog spacetime
λ grep -rn -e "attentionbank"
opencog/opencog/nlp/fuzzy/Fuzzy.cc:27:#include <opencog/attentionbank/bank/AttentionBank.h>
opencog/opencog/nlp/fuzzy/Fuzzy.cc:46:    bank(&attentionbank(as)),
opencog/opencog/nlp/fuzzy/Fuzzy.cc:55:    bank(&attentionbank(as)),
opencog/opencog/nlp/fuzzy/Fuzzy.h:29:#include <opencog/attentionbank/bank/AttentionBank.h>
opencog/opencog/nlp/CMakeLists.txt:22:	# fuzzy depends on attentionbank
opencog/tests/persist/zmq/events/AtomSpacePublisherModuleUTest.cxxtest:124:        attentionbank(as).set_af_size(1);
opencog/tests/persist/zmq/events/AtomSpacePublisherModuleUTest.cxxtest:193:        attentionbank(as).change_av(h, AttentionValue::createAV(30, 50, 0));
opencog/tests/persist/zmq/events/AtomSpacePublisherModuleUTest.cxxtest:230:        attentionbank(as).change_av(h, AttentionValue::createAV(1100, 0, 0));
opencog/tests/persist/zmq/events/AtomSpacePublisherModuleUTest.cxxtest:267:        attentionbank(as).change_av(h2, AttentionValue::createAV(1200, 0, 0));
atomspace/examples/atomspace/values.scm:117:(use-modules (opencog attentionbank))
```

**Comment by linas** [comment]
Let's do it.

**Comment by linas** [comment]
It's cleanup time, continuing to support old bad behavior just causes ongoing trouble, so I merged this :-)

**Pull request merged**
